#!/bin/bash

set -e
echo "Hello Student!"
echo -n "Enter your name: "
read name
echo "Welcome to terminal $name"

mkdir -p /tmp/test
date +'%T' > /tmp/test/mydate.txt
echo "Сохраняем данные"

	for i in {1..10}
	do
	echo $i
	sleep .5
	done

echo "Data saved. continue work"
df -h >> /tmp/test/mydate.txt
mkdir -p /opt/mydate
cp /tmp/test/mydate.txt /opt/mydate/newmydate.txt
	
	for i in {1..5}
	do
	echo $i
	sleep 1
	done

echo "Well done Boss" 
